on:
  push:

jobs:
  my_first_job:
    runs-on: self-hosted
    steps:
      - name: First Job
        run: echo "First Job Completed"

  my_second_job:
    needs: my_first_job
    runs-on: self-hosted
    steps:
      - name: Second Job
        run: |
          echo "Second Job Started"
          echo "Second Job Completed"
